ALTER TABLE campuses ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE campuses ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE campuses ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE campuses ADD COLUMN IF NOT EXISTS principal TEXT;
ALTER TABLE campuses ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE campuses ADD COLUMN IF NOT EXISTS sort INTEGER NOT NULL DEFAULT 0;
ALTER TABLE campuses ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE campuses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_campuses_code_unique ON campuses(code) WHERE code IS NOT NULL;
